package parsing;

public class XMLToken {
    public final static String TOKEN_MINUS = "-";
    public final static String TOKEN_SINGLE_QUOTE = "'";
    public final static String TOKEN_DOUBLE_QUOTE = "\"";
    public final static String TOKEN_PARENTHESES_LEFT = "(";
    public final static String TOKEN_PARENTHESES_RIGHT = ")";
    public final static String TOKEN_PLUS = "+";
    public final static String TOKEN_COMMA = ",";
    public final static String TOKEN_DOT = ".";
    public final static String TOKEN_SLASH = "/";
    public final static String TOKEN_COLON = ":";
    public final static String TOKEN_EQUALS = "=";
    public final static String TOKEN_QUESTION_MARK = "?";
    public final static String TOKEN_SEMICOLON = ";";
    public final static String TOKEN_EXCLAMATION = "!";
    public final static String TOKEN_ASTERISK = "*";
    public final static String TOKEN_HASHTAG = "#";
    public final static String TOKEN_AT_SIGN = "@";
    public final static String TOKEN_DOLLAR = "$";
    public final static String TOKEN_UNDERSCORE = "_";
    public final static String TOKEN_PERCENT = "%";
    public final static String TOKEN_CARET = "^";
    public final static String TOKEN_BIGGER_THAN = ">";
    public final static String TOKEN_SMALLER_THAN = "<";
    public final static String TOKEN_COMMENT_START = "<!--";
    public final static String TOKEN_COMMENT_END = "-->";
    public final static String TOKEN_END_TAG_START = "</";
    public final static String TOKEN_EMPTY_TAG_END = "/>";
    public final static String TOKEN_XML_DECL_START = "<?xml";
    public final static String TOKEN_XML_DECL_END = "?>";
    public final static String TOKEN_VERSION_KEYWORD = "version";
    public final static String TOKEN_STANDALONE_KEYWORD = "standalone";
    public final static String TOKEN_YES_KEYWORD = "yes";
    public final static String TOKEN_NO_KEYWORD = "no";
    public final static String TOKEN_VERSION_1_0 = "1.0";
    public final static String TOKEN_WHITESPACE = " ";
    public final static String TOKEN_TAB = "\t";
    public final static String TOKEN_CARRIAGE_RETURN = "\r";
    public final static String TOKEN_LINEFEED = "\n";
    public final static String R_TOKEN_LETTER = "[a-zA-Z]+";
    public final static String R_TOKEN_DIGIT = "[0-9]+";
    public final static String R_TOKEN_CHARRANGE = "[\\t\\n\\ra-zA-Z0-9]+";
    public final static String R_TOKEN_ATTVAL_SQ = "[^<&']+";
    public final static String R_TOKEN_ATTVAL_DQ = "[^<&\"]+";
    public final static String R_TOKEN_CHARDATA = "[^<&]+";
    public final static String TOKEN_EOF = ((char) -1) + "";
    public final static String LEXER_ERROR = "ERR";
}
